---

- name: gather required facts
  setup:
    gather_subset: [min, virtual]
  when: ansible_distribution is not defined or ansible_distribution_release is not defined

- name: set release specific variables
  include_vars: "../vars/{{ ansible_distribution }}/{{ ansible_distribution_release }}.yml"

- name: install
  include_tasks: install.yml
  when: strongswan_setup == "full" or strongswan_setup == "install"

- name: configure
  import_tasks: configure.yml
  when: strongswan_setup == "full" or strongswan_setup == "configure"
